### ISSUE TITLE
Project rename?

### ISSUE THREAD

**Issue by loteoo** [loteoo/hyperstatic#1]
This is where I'm clueless: how should this be named?

- Hypersite
- Instasite
- Hyperlight
- Bourango
- Snabb (fast in swedish)
- Sokudo (speed in japanese)
- Rapida (fast in spanish)

Simply "Hyperapp site generator"?

I'm all out of ideas

**Comment by craftedsystems** [comment]
Just go with _Hypersite_. It's the only one that makes sense.

**Comment by jorgebucaran** [comment]
@loteoo Hayasa also means speed in Japanese. A couple of name ideas: [Hayabusa](https://en.wikipedia.org/wiki/Hayabusa_(train)#Shinkansen_service_(2011%E2%80%93)) or just [Peregrine](https://en.wikipedia.org/wiki/Peregrine_falcon).

**Comment by loteoo** [comment]
Thanks for the suggestions! I think, if I can get puppeteer to run reliably on Netlify I'll go with `hyperstatic` which jorge suggested on spectrum and sounds pretty cool, and then put a bigger emphasis on the pre-rendering stuff. (It might be possible to serialize state after the Init action/effects have run in the build process, allowing the bundles to have some pre-fetched data to work with. Something clean might be possible)

Else I'll go with `hypersite`! 😂

Next release should also be more stable and with the code cleaned up and documented properly.

**Comment by loteoo** [comment]
Alright get your votes in:
https://www.strawpoll.me/18248490

**Comment by loteoo** [comment]
Hyperstatic it is! Thanks @jorgebucaran for the suggestion!
