### ISSUE TITLE
Add a distribution version

### ISSUE THREAD

**Issue by mdings** [loteoo/hyperstatic#14]
When running hyperstatic in parcel (as per example in [hyperstatic-starter](https://github.com/loteoo/hyperapp-starter)) the source doesn't get transpiled, leading to spread-syntax error in Edge. This can be easily prevented by creating a distribution version of hyperstatic.

Also I noticed that in the utils file Object.fromEntries is called which is also not supported in Edge and might have to be polyfilled.

**Comment by loteoo** [comment]
Closing this since the new typescript version of hyperstatic outputs a "browser ready" compiled bundle
