### ISSUE TITLE
Replace query-string with URLSearchParams

### ISSUE THREAD

**Issue by SkipKayhil** [loteoo/hyperstatic#7]
Hey @loteoo,

Really excited about this project and would love to contribute. I noticed hyperstatic currently has a dependency on the `query-string` package, but as far as I know it's functionality could be replaced by [URLSearchParams](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams).

Would you accept a PR making this swap? I would be willing to write it if so

**Comment by loteoo** [comment]
Hello @SkipKayhil, that's right, using URLSearchParams would be better! I think I simply didn't think about it very much and added in an extra depencency for nothing.

Feel free to create a PR for the swap!

Thank you for the interest in the project as well. I haven't really added much in the past couple months, but definitively plan to work on hyperstatic more in the future!

Feel free to contribute, ask questions and suggest changes, thanks!
